### ISSUE TITLE
"en-UK" Invalid BCP47 Language Tag 

### ISSUE THREAD

**Issue by zrgt** [aas-core-works/aas-core3.0-testgen#16]
"en-UK" is not valid BCP47 language tag, as country tag "UK" is not listed in [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1), it should be "GB"

Please update the language tag here:

https://github.com/aas-core-works/aas-core3.0-testgen/blob/9b43de2edfb1a64d0790856cb54aa9a26ec9483f/aas_core3_0_testgen/fixing.py#L43

**Comment by mristin** [comment]
@zrgt thanks for spotting this! Should we actually include ISO 3166 in https://github.com/aas-core-works/aas-core-meta ?

**Comment by mristin** [comment]
@zrgt Let us first fix the issues https://github.com/aas-core-works/aas-core-meta/issues/288 and https://github.com/aas-core-works/aas-core-meta/issues/289. Then I'll fix this issue in the same wave, and update all SDKs and schemas in bulk.
