### ISSUE TITLE
Wrong language tags?

### ISSUE THREAD

**Issue by cbiehl30** [aas-core-works/aas-core3.0-testgen#20]
Hi, in the following example, isn't value of `language` supposed to be a BCP47 tag instead of this long string?

https://github.com/aas-core-works/aas-core3.0-testgen/blob/11ca4988a6cc927e0e64504d53f85db2b4218142/test_data/Json/ContainedInEnvironment/Expected/Submodel/maximal.json#L6-L11

**Comment by mristin** [comment]
Hi @cbiehl30 ,
BCP47 tags are "dynamic" in the sense that they depend on political decisions, and change frequently. We decided in the end to only check for regular expressions according to the [BCP 47], but not to keep an up-to-date list. Hence, the cited tag is valid, but not actually existing.

We fuzzed it using the pattern from [BCP 47].

[BCP 47]: https://www.rfc-editor.org/rfc/bcp/bcp47.txt

**Comment by cbiehl30** [comment]
I understand. Thanks!
